Repository SSUMC-8th/Spring_Boot_C, pull requests merged in 2025-05, with the labels that each got.

#19 [Mori] Chatper 6. JPA 활용
  .gitignore
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Location.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/mapping/MemberMission.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Chapter06

#24 [Kara] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QAgree.java
  src/main/generated/umc/spring/domain/QFood.java
  src/main/generated/umc/spring/domain/QInquiry.java
  src/main/generated/umc/spring/domain/QInquiryImg.java
  src/main/generated/umc/spring/domain/QLocation.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewImg.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QStoreHour.java
  src/main/generated/umc/spring/domain/QStoreImg.java
  src/main/generated/umc/spring/domain/QUser.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QUserAgree.java
  src/main/generated/umc/spring/domain/mapping/QUserFood.java
  src/main/generated/umc/spring/domain/mapping/QUserMission.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Location.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#21 [Roggi] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewPhoto.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QStoreHours.java
  src/main/generated/umc/spring/domain/QStorePhoto.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberFood.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberTerms.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#30 [Roggi] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#28 [Mori] Chapter 7. API 응답 통일 & 에러 핸들러
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/dto/MemberDto.java
  src/main/java/umc/spring/dto/MissionCursorResponseDto.java
  src/main/java/umc/spring/dto/MissionProgressDto.java
  src/main/java/umc/spring/exception/ExceptionAdvice.java
  src/main/java/umc/spring/exception/GeneralException.java
  src/main/java/umc/spring/exception/handler/TempHandler.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MemberMissionRepositoryCustom.java
  src/main/java/umc/spring/repository/MemberMissionRepositoryCustomImpl.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/MemberRepositoryCustom.java
  src/main/java/umc/spring/repository/MemberRepositoryCustomImpl.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/ReviewService.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#38 [Kara] Chapter 8. API & Swagger & Annotation
  build.gradle
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QUser.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/FoodCategoryHandler.java
  src/main/java/umc/spring/config/SwaggerConfig.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/converter/MemberPreferConverter.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/User.java
  src/main/java/umc/spring/domain/enums/FoodCategory.java
  src/main/java/umc/spring/domain/enums/Gender.java
  src/main/java/umc/spring/domain/mapping/UserFood.java
  src/main/java/umc/spring/domain/mapping/UserMission.java
  src/main/java/umc/spring/repository/FoodRepository/FoodCategoryRepository.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/spring/repository/MissionRepository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreCommandService.java
  src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistCategories.java
  src/main/java/umc/spring/validation/annotation/ExistMember.java
  src/main/java/umc/spring/validation/annotation/ExistMemberMissionMission.java
  src/main/java/umc/spring/validation/annotation/ExistStore.java
  src/main/java/umc/spring/validation/validator/CategoriesExistValidator.java
  src/main/java/umc/spring/validation/validator/MemberExistValidator.java
  src/main/java/umc/spring/validation/validator/MemberMissionExistValidator.java
  src/main/java/umc/spring/validation/validator/StoreExistValidator.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/MemberMissionResponseDTO.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/java/umc/spring/web/dto/MemberResponseDTO.java
  src/main/java/umc/spring/web/dto/MissionRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08

#37 [Roggi] Chapter 8. API & Swagger & Annotation
  build.gradle
  src/main/java/umc/spring/apiPayload/code/MemberRequestDTO.java
  src/main/java/umc/spring/apiPayload/code/MemberResponseDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/handler/FoodCategoryHandler.java
  src/main/java/umc/spring/config/SwaggerConfig.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/converter/MemberFoodConverter.java
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/mapping/MemberFood.java
  src/main/java/umc/spring/repository/FoodCategoryRepository.java
  src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/MissoinRepository/MissionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandService.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandServiceImpl.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionQueryService.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionQueryServiceImpl.java
  src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistCategories.java
  src/main/java/umc/spring/validation/annotation/NotAlreadyChallenging.java
  src/main/java/umc/spring/validation/annotation/ValidStoreId.java
  src/main/java/umc/spring/validation/validator/CategoriesExistValidator.java
  src/main/java/umc/spring/validation/validator/NotAlreadyChallengingValidator.java
  src/main/java/umc/spring/validation/validator/StoreIdValidator.java
  src/main/java/umc/spring/web/controller/MemberMissionRestController.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/controller/ReviewRestController.java
  src/main/java/umc/spring/web/dto/MissionChallengeRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionChallengeResponseDTO.java
  src/main/java/umc/spring/web/dto/MissionCreateRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionCreateResponseDTO.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08

#46 [Kara] Chapter 9. API & Paging
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/MissionRepository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ValidPage.java
  src/main/java/umc/spring/validation/validator/PageValidator.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter09

#44 [Hans] Chapter 9. API & Paging
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/study/converter/MissionConverter.java
  src/main/java/umc/study/converter/ReviewConverter.java
  src/main/java/umc/study/converter/StoreConverter.java
  src/main/java/umc/study/converter/UserMissionConverter.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewOwnerReply.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/study/repository/UserMissionRepository/UserMissionRepository.java
  src/main/java/umc/study/service/MissionService/MissionQueryService.java
  src/main/java/umc/study/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/study/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/study/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/study/service/UserMissionService/UserMissionQueryService.java
  src/main/java/umc/study/service/UserMissionService/UserMissionQueryServiceImpl.java
  src/main/java/umc/study/validation/annotation/ExistStore.java
  src/main/java/umc/study/validation/annotation/ValidPage.java
  src/main/java/umc/study/validation/validator/ExistStoreValidator.java
  src/main/java/umc/study/validation/validator/ValidPageValidator.java
  src/main/java/umc/study/web/controller/MissionRestController.java
  src/main/java/umc/study/web/controller/StoreRestController.java
  src/main/java/umc/study/web/controller/UserMissionRestController.java
  src/main/java/umc/study/web/controller/UserRestController.java
  src/main/java/umc/study/web/dto/MissionDTO/MissionPreviewDTO.java
  src/main/java/umc/study/web/dto/MissionDTO/MissionPreviewListDTO.java
  src/main/java/umc/study/web/dto/UserMissionDTO/MyOngoingMissionDTO.java
  src/main/java/umc/study/web/dto/UserMissionDTO/MyOngoingMissionListDTO.java
  src/main/java/umc/study/web/dto/responseDTO/StoreResponseDTO.java
  src/main/java/umc/study/web/dto/reviewDTO/MyReviewDTO.java
  src/main/java/umc/study/web/dto/reviewDTO/MyReviewListDTO.java
  src/main/java/umc/study/web/dto/reviewDTO/OwnerReplyDTO.java
Labels: ✨ Chapter09

#55 [Roggi] Chapter 10. 로그인 및 회원가입
  build.gradle
  src/main/generated/umc/spring/domain/QMember.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/code/MemberRequestDTO.java
  src/main/java/umc/spring/apiPayload/code/MemberResponseDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/spring/config/properties/Constants.java
  src/main/java/umc/spring/config/properties/JwtProperties.java
  src/main/java/umc/spring/config/security/CustomUserDetailsService.java
  src/main/java/umc/spring/config/security/SecurityConfig.java
  src/main/java/umc/spring/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/spring/config/security/jwt/JwtTokenProvider.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/enums/Role.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/java/umc/spring/web/dto/MemberResponseDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/admin.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: ✨ Chapter10

#54 [Mori] Chapter 10. 로그인 및 회원 가입
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/config/properties/Constants.java
  src/main/java/umc/spring/config/properties/JwtProperties.java
  src/main/java/umc/spring/config/security/CustomUserDetailsService.java
  src/main/java/umc/spring/config/security/SecurityConfig.java
  src/main/java/umc/spring/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/spring/config/security/jwt/JwtTokenProvider.java
  src/main/java/umc/spring/controller/MemberRestController.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/enums/Role.java
  src/main/java/umc/spring/dto/web/MemberRequestDTO.java
  src/main/java/umc/spring/dto/web/MemberResponseDTO.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/service/memberservice/MemberCommandService.java
  src/main/java/umc/spring/service/memberservice/MemberCommandServiceImpl.java
  src/main/java/umc/spring/service/memberservice/MemberQueryService.java
  src/main/java/umc/spring/service/memberservice/MemberQueryServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/admin.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: ✨ Chapter10
